GR1:
  name: "CEO Rule"
  min_amount: 2
  relative_discount: 0.5
  round: :floor
SR1:
  name: "COO rule"
  min_amount: 3
  absolute_discount: 0.5
CF1:
  name: "VP of Engineering rule"
  min_amount: 3
  relative_discount: 0.333333333